import React from 'react'
import Layout from '../components/layout'
import { loadFirebase } from '../lib/firebase'

export default function Importer() {
  const firebase = loadFirebase()
  const db = firebase.firestore()

  const brukere = [
    {
      fornavn: 'Daniel',
      etternavn: 'Martinsen',
      bursdag: '130204',
      telefon: '91001793',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Torbjørn',
      etternavn: 'Ørka',
      bursdag: '170604',
      telefon: '40524030',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Casper',
      etternavn: 'Ruud',
      bursdag: '140704',
      telefon: '46836107',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Isabell',
      etternavn: 'Møller',
      bursdag: '170401',
      telefon: '95454726',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Lars ',
      etternavn: 'Svendstad',
      bursdag: '230901',
      telefon: '40522040',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Joachim',
      etternavn: 'Tettum',
      bursdag: '260804',
      telefon: '90884626',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Bjørn-Erik',
      etternavn: 'Pedersen',
      bursdag: '300970',
      telefon: '97464947',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Marcus',
      etternavn: 'Koppervik',
      bursdag: '010803',
      telefon: '48222354',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Adrian',
      etternavn: 'Kristiansen',
      bursdag: '281003',
      telefon: '41586798',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Åsmund',
      etternavn: 'Lerkelund',
      bursdag: '260403',
      telefon: '48042063',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Viljar',
      etternavn: 'Orre',
      bursdag: '300705',
      telefon: '48437880',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Eirik',
      etternavn: 'Eikemo',
      bursdag: '211205',
      telefon: '97698897',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Emil',
      etternavn: 'Huss-Brøste',
      bursdag: '110805',
      telefon: '46515339',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jonathan ',
      etternavn: 'Jansson',
      bursdag: '050806',
      telefon: '94031322',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Simon',
      etternavn: 'Champasith-Laugen',
      bursdag: '160904',
      telefon: '97462847',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Per-Kristian',
      etternavn: 'Olsen',
      bursdag: '120100',
      telefon: '40831048',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Magnus',
      etternavn: 'Kvarme',
      bursdag: '150805',
      telefon: '46851088',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Vu An',
      etternavn: 'Nguyen ',
      bursdag: '090405',
      telefon: '90929490',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Øyvind',
      etternavn: 'Røsvik',
      bursdag: '040705',
      telefon: '45771135',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Eirik',
      etternavn: 'Elind',
      bursdag: '220605',
      telefon: '40541819',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'San',
      etternavn: 'Ako',
      bursdag: '310805',
      telefon: '45801378',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Arin',
      etternavn: 'Olsen',
      bursdag: '100706',
      telefon: '48395788',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mathias',
      etternavn: 'Skuterud',
      bursdag: '100806',
      telefon: '48023518',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Odin',
      etternavn: 'Buhler',
      bursdag: '1009',
      telefon: '45394224',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jonas',
      etternavn: 'Nesfeldt',
      bursdag: '250705',
      telefon: '90075089',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Herman',
      etternavn: 'Sildnes',
      bursdag: '280303',
      telefon: '90011121',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jonathan',
      etternavn: 'Jensen',
      bursdag: '290405',
      telefon: '93286350',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Felix',
      etternavn: 'Fiske',
      bursdag: '280205',
      telefon: '40195165',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jeg heter sander',
      etternavn: 'Garen',
      bursdag: '1213',
      telefon: '90829878',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jakob',
      etternavn: 'Andresen',
      bursdag: '250205',
      telefon: '46637830',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Amund',
      etternavn: 'Chhetri',
      bursdag: '280106',
      telefon: '45838152',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Petter',
      etternavn: 'Strandrud',
      bursdag: '240706',
      telefon: '94810039',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Leo',
      etternavn: 'Klech',
      bursdag: '280106',
      telefon: '41218777',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Arimantas',
      etternavn: 'Belousovas',
      bursdag: '010605',
      telefon: '46665270',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Michias',
      etternavn: 'Ejigu',
      bursdag: '280906',
      telefon: '93825464',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Anders',
      etternavn: 'Frydenlund ',
      bursdag: '221006',
      telefon: '46283464',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mathias',
      etternavn: 'Rånås',
      bursdag: '081206',
      telefon: '45257852',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Birk',
      etternavn: 'Lilleheier',
      bursdag: '290306',
      telefon: '94980902',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jakob',
      etternavn: 'Skeie',
      bursdag: '170806',
      telefon: '46123764',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jakob',
      etternavn: 'Koch',
      bursdag: '270206',
      telefon: '40393140',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jonas',
      etternavn: 'Larsen',
      bursdag: '220306',
      telefon: '46960269',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Sivert',
      etternavn: 'Eggerud',
      bursdag: '010806',
      telefon: '95403464',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Håkon',
      etternavn: 'Bergseng',
      bursdag: '110806',
      telefon: '41432211',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Martin',
      etternavn: 'Ånestad',
      bursdag: '231006',
      telefon: '48457414',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Torje',
      etternavn: 'Gilbert',
      bursdag: '250106',
      telefon: '97774046',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Oscar',
      etternavn: 'Almås',
      bursdag: '280105',
      telefon: '92139762',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Edgar',
      etternavn: 'Nilsen',
      bursdag: '080406',
      telefon: '46318919',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Benedikte',
      etternavn: 'Haugom børresen',
      bursdag: '010405',
      telefon: '48077383',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Aki',
      etternavn: 'Stojanovic',
      bursdag: '130105',
      telefon: '48670971',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Christian',
      etternavn: 'Aanesland',
      bursdag: '030206',
      telefon: '98873933',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Esrom',
      etternavn: 'Mussie',
      bursdag: '110205',
      telefon: '45574188',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Dalil',
      etternavn: 'Ibrahim',
      bursdag: '281004',
      telefon: '97362956',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Henrik',
      etternavn: 'Slåtsveen',
      bursdag: '271106',
      telefon: '91528406',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Elyas',
      etternavn: 'Namen',
      bursdag: '241204',
      telefon: '94731399',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Ryan',
      etternavn: 'Noryan',
      bursdag: '190705',
      telefon: '45782823',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Sondre',
      etternavn: 'Brovold',
      bursdag: '281105',
      telefon: '92272811',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Konrad',
      etternavn: 'Nordbakken ',
      bursdag: '230805',
      telefon: '91561514',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Martin',
      etternavn: 'Dalsrud',
      bursdag: '030906',
      telefon: '40083026',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Linnea',
      etternavn: 'Sæther',
      bursdag: '060806',
      telefon: '48433733',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Koket',
      etternavn: 'Kebede',
      bursdag: '300907',
      telefon: '46258840',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Firaol',
      etternavn: 'Kebede',
      bursdag: '2105',
      telefon: '92541115',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Birk',
      etternavn: 'Wiig',
      bursdag: '291104',
      telefon: '46839704',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Marte',
      etternavn: 'Amundstad',
      bursdag: '130106',
      telefon: '94161329',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Bo',
      etternavn: 'Guttormsen',
      bursdag: '020706',
      telefon: '95494114',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Silas',
      etternavn: 'Bakke',
      bursdag: '080606',
      telefon: '98364216',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Fredrik',
      etternavn: 'Kristiansen',
      bursdag: '310803',
      telefon: '95852716',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Adrian',
      etternavn: 'Ruud',
      bursdag: '1',
      telefon: '95825856',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Kristian',
      etternavn: 'Smedsrud',
      bursdag: '151105',
      telefon: '93084430',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'William',
      etternavn: 'Fjell',
      bursdag: '200406',
      telefon: '48341067',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Bjørn',
      etternavn: 'Pollen',
      bursdag: '241206',
      telefon: '92143364',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Thor',
      etternavn: 'Svendstad',
      bursdag: '040607',
      telefon: '40547502',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Asraa',
      etternavn: 'Watheq',
      bursdag: '200106',
      telefon: '45857755',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mina',
      etternavn: 'Ari',
      bursdag: '090106',
      telefon: '46318712',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Rayan',
      etternavn: 'Suliman',
      bursdag: '020705',
      telefon: '94265332',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Vetle',
      etternavn: 'Johnson',
      bursdag: '150104',
      telefon: '90077493',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Remi',
      etternavn: 'Edvardsen',
      bursdag: '200604',
      telefon: '41449676',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Sondre',
      etternavn: 'Engøy',
      bursdag: '190804',
      telefon: '48298853',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Niklas',
      etternavn: 'Solheim',
      bursdag: '230804',
      telefon: '48443959',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Lennard Rolstad',
      etternavn: 'Denby',
      bursdag: '120104',
      telefon: '46517270',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Martin',
      etternavn: 'Hilstad',
      bursdag: '300704',
      telefon: '94054025',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Oscar',
      etternavn: 'Lübeck',
      bursdag: '040804',
      telefon: '40051181',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Luc',
      etternavn: 'Meuwissen',
      bursdag: '010105',
      telefon: '94056396',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Didrik',
      etternavn: 'Sviu',
      bursdag: '2005628',
      telefon: '98600053',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Dawid',
      etternavn: 'Wysocki',
      bursdag: '8122005',
      telefon: '99373321',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mikael',
      etternavn: 'Bruland',
      bursdag: '270701',
      telefon: '95738833',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Marcus',
      etternavn: 'Koppervik',
      bursdag: '010803',
      telefon: '48222354',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Kristoffer',
      etternavn: 'Graue',
      bursdag: '250303',
      telefon: '98764454',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Matias',
      etternavn: 'Brantseg',
      bursdag: '290406',
      telefon: '47979603',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Bjørn Ivar',
      etternavn: 'Dørdal',
      bursdag: '180701',
      telefon: '91851092',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Sindre',
      etternavn: 'Horn',
      bursdag: '030501',
      telefon: '97876803',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Henrik',
      etternavn: 'Erdal',
      bursdag: '180712',
      telefon: '95939663',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Stian',
      etternavn: 'Olsen',
      bursdag: '300404',
      telefon: '95014273',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Tobias',
      etternavn: 'Petterson',
      bursdag: '04',
      telefon: '95802760',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Aleksander ',
      etternavn: 'Smedal',
      bursdag: '04',
      telefon: '92983230',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mikkel',
      etternavn: 'Vaaje-Kolstad',
      bursdag: '151004',
      telefon: '48441930',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Anders',
      etternavn: 'Bredal-Andersen',
      bursdag: '270704',
      telefon: '99500939',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Daniel',
      etternavn: 'Asalf',
      bursdag: '081205',
      telefon: '93013737',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Marko',
      etternavn: 'Lazarevic',
      bursdag: '230805',
      telefon: '92169007',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Anders',
      etternavn: 'Lileng',
      bursdag: '290507',
      telefon: '12345678',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jan ',
      etternavn: 'Grzegorzak',
      bursdag: '110707',
      telefon: '92219781',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Lavrans',
      etternavn: 'Grindflek',
      bursdag: '230404',
      telefon: '99443305',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Sara',
      etternavn: 'Josefsen',
      bursdag: '231104',
      telefon: '90779253',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Leon',
      etternavn: 'Halvorsen',
      bursdag: '010607',
      telefon: '98549302',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Helena',
      etternavn: 'Vivian-Smith ',
      bursdag: '160705',
      telefon: '90625964',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Laura Melissa ',
      etternavn: 'Haukelidsæter',
      bursdag: '060905',
      telefon: '99237201',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Ada signe',
      etternavn: 'Myhren',
      bursdag: '040505',
      telefon: '46880638',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Kristian',
      etternavn: 'Hilstad',
      bursdag: '300704',
      telefon: '94053866',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mia',
      etternavn: 'Skotland',
      bursdag: '171206',
      telefon: '48174925',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Maria',
      etternavn: 'Alem',
      bursdag: '7306',
      telefon: '96907211',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Remi',
      etternavn: 'Edvardsen',
      bursdag: '200604',
      telefon: '41449676',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Emil',
      etternavn: 'Hallingstad',
      bursdag: '170204',
      telefon: '95557574',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mikkel',
      etternavn: 'Hallinstad',
      bursdag: '170204',
      telefon: '95557576',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Caroline',
      etternavn: 'Sollie',
      bursdag: '080204',
      telefon: '94816107',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Aleksander',
      etternavn: 'Brantseg',
      bursdag: '090703',
      telefon: '45617466',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Casper',
      etternavn: 'Olsen',
      bursdag: '250203',
      telefon: '90033900',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Bjørn',
      etternavn: 'Færgestad',
      bursdag: '140303',
      telefon: '97706672',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jonas',
      etternavn: 'Svendsen',
      bursdag: '221103',
      telefon: '98105322',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mathias',
      etternavn: 'Heimsæter',
      bursdag: '310703',
      telefon: '99570069',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Tobias',
      etternavn: 'Schie',
      bursdag: '031003',
      telefon: '45064152',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Stivert',
      etternavn: 'Syre',
      bursdag: '100602',
      telefon: '46945272',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Alexandra',
      etternavn: 'Zetlitz',
      bursdag: '290503',
      telefon: '48119029',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Emma',
      etternavn: 'Martinsen',
      bursdag: '040804',
      telefon: '97756484',
      kjonn: 'jenye',
    },
    {
      fornavn: 'Andréa',
      etternavn: 'Stubberud',
      bursdag: '231103',
      telefon: '90958065',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Andréa',
      etternavn: 'Stubberud',
      bursdag: '231103',
      telefon: '90958065',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Andréa',
      etternavn: 'Stubberud',
      bursdag: '231103',
      telefon: '90958065',
      kjonn: 'Jente',
    },
    {
      fornavn: 'Andréa',
      etternavn: 'Stubberud',
      bursdag: '231103',
      telefon: '90958065',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Arin',
      etternavn: 'Ritchie',
      bursdag: '190804',
      telefon: '91993393',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Amanuel',
      etternavn: 'Ejigu',
      bursdag: '07012004',
      telefon: '45546924',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Mehiretab',
      etternavn: 'Melesse',
      bursdag: '280504',
      telefon: '45051706',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Eyoel',
      etternavn: 'Tesfaye',
      bursdag: '021205',
      telefon: '40146315',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Victor',
      etternavn: 'Bafelt',
      bursdag: '241002',
      telefon: '47206080',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Ulrik',
      etternavn: 'Barfelt',
      bursdag: '250901',
      telefon: '47206090',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Oscar ',
      etternavn: 'Grue',
      bursdag: '051201',
      telefon: '40602072',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Thea ',
      etternavn: 'Werner',
      bursdag: '270406',
      telefon: '90060142',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Kristian',
      etternavn: 'Ask',
      bursdag: '271106',
      telefon: '98769914',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Aurora',
      etternavn: 'Skåre',
      bursdag: '310305',
      telefon: '97613967',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Eunice',
      etternavn: 'Compaore',
      bursdag: '4604',
      telefon: '95555102',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Viktoria',
      etternavn: 'Leinhardt',
      bursdag: '191201',
      telefon: '90912293',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Michael',
      etternavn: 'Mugeni',
      bursdag: '2562007',
      telefon: '46725206',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Daniel',
      etternavn: 'Miguel',
      bursdag: '250807',
      telefon: '46633067',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Daniel',
      etternavn: 'Miguel',
      bursdag: '250807',
      telefon: '46633067',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Martin',
      etternavn: 'Hvattum',
      bursdag: '071204',
      telefon: '95910239',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Joaquin ',
      etternavn: 'Lozano',
      bursdag: '29402007',
      telefon: '46531377',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Jantresor',
      etternavn: 'Kamanou',
      bursdag: '21',
      telefon: '46521537',
      kjonn: 'Gutt',
    },
    {
      fornavn: 'Timeo',
      etternavn: 'Kamanou',
      bursdag: '210910',
      telefon: '46521537',
      kjonn: 'Gutt',
    },
  ]

  const increment = firebase.firestore.FieldValue.increment(1)

  function runImport() {
    var userID = 99

    brukere.map((bruker) => {
      userID++

      const statsRef = db
        .collection('Kunder')
        .doc('OkUHO5TZNpGgdmxgpuTZg3XSzqaVzF4B')
        .collection('Brukere')
        .doc('--stats--')

      const userRef = db
        .collection('Kunder')
        .doc('OkUHO5TZNpGgdmxgpuTZg3XSzqaVzF4B')
        .collection('Brukere')
        .doc(userID.toString())

      const batch = db.batch()

      bruker.innsjekk = { dato: '', klokkeslett: '' }
      bruker.innsjekkCount = 0

      batch.set(statsRef, { userCount: increment }, { merge: true })
      batch.set(userRef, bruker)
      batch.commit().then(() => {
        console.log('Registrert')
      })
    })
  }

  return (
    <Layout title=''>
      <button onClick={(e) => runImport()}>IMPORTER</button>
    </Layout>
  )
}
